### ISSUE TITLE
Keeping the Coretto JDKs up to date?

### ISSUE THREAD

**Issue by Freakin** [making/amazon-corretto-buildpack#1]
Who maintains the tarballs of Coretto in the `index.yml`?  Can this be updated with new versions as they are released?

Alternatively, can instructions be provided for preparing a release of Coretto to be consumable by `java-buildpack` so users/operators can self-maintain where required?

**Comment by making** [comment]
The tar files are maintained by Amazon
Look the links of `amazon-corretto-*-linux-x64.tar.gz`
https://github.com/corretto/corretto-11/releases
you can easily maintain your own `index.yml`
